# Generated by Django 2.2.5 on 2020-05-31 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmd_controller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandcontroller',
            name='script_name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
